// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogDocumentDataSlicesSlice =
  | NewsLetterSlice
  | ArticleSectionSlice
  | SplitContentSlice
  | ImageGroupSlice;

/**
 * Content for blog documents
 */
interface BlogDocumentData {
  /**
   * Card Image field in *blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.card_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  card_image: prismic.ImageField<never>;

  /**
   * Card Heading field in *blog*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter card heading here...
   * - **API ID Path**: blog.card_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  card_heading: prismic.RichTextField;

  /**
   * Button field in *blog*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter your button name...
   * - **API ID Path**: blog.button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Slice Zone field in *blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice>;
}

/**
 * blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;

type BlogsDocumentDataSlicesSlice = NewsLetterSlice;

/**
 * Content for Blogs documents
 */
interface BlogsDocumentData {
  /**
   * banner image field in *Blogs*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs.banner_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner_image: prismic.ImageField<never>;

  /**
   * title field in *Blogs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter title here...
   * - **API ID Path**: blogs.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Blogs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter sub description here...
   * - **API ID Path**: blogs.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Slice Zone field in *Blogs*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogsDocumentDataSlicesSlice>;
}

/**
 * Blogs document from Prismic
 *
 * - **API ID**: `blogs`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<BlogsDocumentData>, "blogs", Lang>;

/**
 * Item in *Footer → Nav*
 */
export interface FooterDocumentDataNavItem {
  /**
   * Nav Link field in *Footer → Nav*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter your nav link here...
   * - **API ID Path**: footer.nav[].nav_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  nav_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *Footer → social*
 */
export interface FooterDocumentDataSocialItem {
  /**
   * social type field in *Footer → social*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Enter social type here...
   * - **API ID Path**: footer.social[].social_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  social_type: prismic.SelectField<"facebook" | "instagram" | "youtube">;

  /**
   * social link field in *Footer → social*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter your link here...
   * - **API ID Path**: footer.social[].social_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Description field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter sub description here...
   * - **API ID Path**: footer.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Nav field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.nav[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  nav: prismic.GroupField<Simplify<FooterDocumentDataNavItem>>;

  /**
   * copyright field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter copyright text here...
   * - **API ID Path**: footer.copyright
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyright: prismic.KeyTextField;

  /**
   * Privacy field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter your privacy placeholder...
   * - **API ID Path**: footer.privacy
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  privacy: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Terms field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter terms placeholder here....
   * - **API ID Path**: footer.terms
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  terms: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * social field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social: prismic.GroupField<Simplify<FooterDocumentDataSocialItem>>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *Header → Nav*
 */
export interface HeaderDocumentDataNavItem {
  /**
   * Nav Link field in *Header → Nav*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter your nav link here...
   * - **API ID Path**: header.nav[].nav_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  nav_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *Header → social*
 */
export interface HeaderDocumentDataSocialItem {
  /**
   * social link field in *Header → social*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter your social link here...
   * - **API ID Path**: header.social[].social_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * social type field in *Header → social*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select your type
   * - **API ID Path**: header.social[].social_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  social_type: prismic.SelectField<"facebook" | "instagram" | "youtube">;
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Logo field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Nav field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.nav[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  nav: prismic.GroupField<Simplify<HeaderDocumentDataNavItem>>;

  /**
   * social field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.social[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social: prismic.GroupField<Simplify<HeaderDocumentDataSocialItem>>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | NewsLetterSlice
  | ArticleSectionSlice
  | SalesSectionSlice
  | CardSectionSlice
  | HeroSliderSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | ContactFormSlice
  | CardSectionSlice
  | ContentSectionSlice
  | SalesSectionSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes =
  | BlogDocument
  | BlogsDocument
  | FooterDocument
  | HeaderDocument
  | HomepageDocument
  | PageDocument;

/**
 * Item in *ArticleSection → Default → Primary → Featured Blog*
 */
export interface ArticleSectionSliceDefaultPrimaryFeaturedBlogItem {
  /**
   * Featured Blog field in *ArticleSection → Default → Primary → Featured Blog*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: article_section.default.primary.featured_blog[].featured_blog
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  featured_blog: prismic.ContentRelationshipField<"blog">;

  /**
   * With Date field in *ArticleSection → Default → Primary → Featured Blog*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: article_section.default.primary.featured_blog[].with_date
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  with_date: prismic.BooleanField;
}

/**
 * Primary content in *ArticleSection → Default → Primary*
 */
export interface ArticleSectionSliceDefaultPrimary {
  /**
   * Heading field in *ArticleSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter heading here...
   * - **API ID Path**: article_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Button field in *ArticleSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter button name...
   * - **API ID Path**: article_section.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Featured Blog field in *ArticleSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: article_section.default.primary.featured_blog[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  featured_blog: prismic.GroupField<
    Simplify<ArticleSectionSliceDefaultPrimaryFeaturedBlogItem>
  >;
}

/**
 * Default variation for ArticleSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticleSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ArticleSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ArticleSection*
 */
type ArticleSectionSliceVariation = ArticleSectionSliceDefault;

/**
 * ArticleSection Shared Slice
 *
 * - **API ID**: `article_section`
 * - **Description**: ArticleSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticleSectionSlice = prismic.SharedSlice<
  "article_section",
  ArticleSectionSliceVariation
>;

/**
 * Item in *CardSection → Default → Primary → Cards*
 */
export interface CardSectionSliceDefaultPrimaryCardsItem {
  /**
   * Card icon field in *CardSection → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: card_section.default.primary.cards[].card_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  card_icon: prismic.ImageField<never>;

  /**
   * Heading field in *CardSection → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter card heading...
   * - **API ID Path**: card_section.default.primary.cards[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *CardSection → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter sub description here...
   * - **API ID Path**: card_section.default.primary.cards[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Item in *CardSection → Card with center align → Primary → Cards*
 */
export interface CardSectionSliceCardWithCenterAlignPrimaryCardsItem {
  /**
   * Card icon field in *CardSection → Card with center align → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: card_section.cardWithCenterAlign.primary.cards[].card_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  card_icon: prismic.ImageField<never>;

  /**
   * Heading field in *CardSection → Card with center align → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter card heading...
   * - **API ID Path**: card_section.cardWithCenterAlign.primary.cards[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *CardSection → Card with center align → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter sub description here...
   * - **API ID Path**: card_section.cardWithCenterAlign.primary.cards[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *CardSection → Default → Primary*
 */
export interface CardSectionSliceDefaultPrimary {
  /**
   * Cards field in *CardSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: card_section.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cards: prismic.GroupField<Simplify<CardSectionSliceDefaultPrimaryCardsItem>>;

  /**
   * Background Color field in *CardSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select background color...
   * - **Default Value**: bg-white
   * - **API ID Path**: card_section.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"bg-white" | "bg_primary", "filled">;
}

/**
 * Default variation for CardSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CardSection → Card with center align → Primary*
 */
export interface CardSectionSliceCardWithCenterAlignPrimary {
  /**
   * Cards field in *CardSection → Card with center align → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: card_section.cardWithCenterAlign.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cards: prismic.GroupField<
    Simplify<CardSectionSliceCardWithCenterAlignPrimaryCardsItem>
  >;

  /**
   * Heading field in *CardSection → Card with center align → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter heading here...
   * - **API ID Path**: card_section.cardWithCenterAlign.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Card with center align variation for CardSection Slice
 *
 * - **API ID**: `cardWithCenterAlign`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardSectionSliceCardWithCenterAlign = prismic.SharedSliceVariation<
  "cardWithCenterAlign",
  Simplify<CardSectionSliceCardWithCenterAlignPrimary>,
  never
>;

/**
 * Slice variation for *CardSection*
 */
type CardSectionSliceVariation =
  | CardSectionSliceDefault
  | CardSectionSliceCardWithCenterAlign;

/**
 * CardSection Shared Slice
 *
 * - **API ID**: `card_section`
 * - **Description**: CardSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardSectionSlice = prismic.SharedSlice<
  "card_section",
  CardSectionSliceVariation
>;

/**
 * Item in *ContactForm → Default → Primary → Form Input*
 */
export interface ContactFormSliceDefaultPrimaryFormInputItem {
  /**
   * Input Label field in *ContactForm → Default → Primary → Form Input*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter your Input label...
   * - **API ID Path**: contact_form.default.primary.form_input[].input_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_label: prismic.KeyTextField;

  /**
   * Input Placeholder field in *ContactForm → Default → Primary → Form Input*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter placeholder here....
   * - **API ID Path**: contact_form.default.primary.form_input[].input_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_placeholder: prismic.KeyTextField;

  /**
   * Form Field field in *ContactForm → Default → Primary → Form Input*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select your form field...
   * - **Default Value**: input
   * - **API ID Path**: contact_form.default.primary.form_input[].form_field
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  form_field: prismic.SelectField<"input" | "textarea", "filled">;

  /**
   * input id field in *ContactForm → Default → Primary → Form Input*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter input id...
   * - **API ID Path**: contact_form.default.primary.form_input[].input_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_id: prismic.KeyTextField;
}

/**
 * Primary content in *ContactForm → Default → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
  /**
   * Form Input field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.form_input[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  form_input: prismic.GroupField<
    Simplify<ContactFormSliceDefaultPrimaryFormInputItem>
  >;

  /**
   * Button field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Enter your button name...
   * - **API ID Path**: contact_form.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * map field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter map link here....
   * - **API ID Path**: contact_form.default.primary.map
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  map: prismic.KeyTextField;
}

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Primary content in *ContentSection → Default → Primary*
 */
export interface ContentSectionSliceDefaultPrimary {
  /**
   * Heading field in *ContentSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter heading here...
   * - **API ID Path**: content_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *ContentSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter sub description here...
   * - **API ID Path**: content_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for ContentSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentSection*
 */
type ContentSectionSliceVariation = ContentSectionSliceDefault;

/**
 * ContentSection Shared Slice
 *
 * - **API ID**: `content_section`
 * - **Description**: ContentSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSectionSlice = prismic.SharedSlice<
  "content_section",
  ContentSectionSliceVariation
>;

/**
 * Item in *HeroSlider → Default → Primary → SliderImage*
 */
export interface HeroSliderSliceDefaultPrimarySliderImageItem {
  /**
   * Image field in *HeroSlider → Default → Primary → SliderImage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slider.default.primary.sliderImage[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *HeroSlider → Default → Primary*
 */
export interface HeroSliderSliceDefaultPrimary {
  /**
   * Heading field in *HeroSlider → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter heading here...
   * - **API ID Path**: hero_slider.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *HeroSlider → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter sub description here...
   * - **API ID Path**: hero_slider.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * SliderImage field in *HeroSlider → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slider.default.primary.sliderImage[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sliderImage: prismic.GroupField<
    Simplify<HeroSliderSliceDefaultPrimarySliderImageItem>
  >;
}

/**
 * Default variation for HeroSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSlider*
 */
type HeroSliderSliceVariation = HeroSliderSliceDefault;

/**
 * HeroSlider Shared Slice
 *
 * - **API ID**: `hero_slider`
 * - **Description**: HeroSlider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliderSlice = prismic.SharedSlice<
  "hero_slider",
  HeroSliderSliceVariation
>;

/**
 * Item in *ImageGroup → Default → Primary → Group Image*
 */
export interface ImageGroupSliceDefaultPrimaryGroupImageItem {
  /**
   * Image field in *ImageGroup → Default → Primary → Group Image*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_group.default.primary.group_image[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *ImageGroup → Default → Primary → Content*
 */
export interface ImageGroupSliceDefaultPrimaryContentItem {
  /**
   * heading field in *ImageGroup → Default → Primary → Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter heading here....
   * - **API ID Path**: image_group.default.primary.content[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *ImageGroup → Default → Primary → Content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter sub description here...
   * - **API ID Path**: image_group.default.primary.content[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *ImageGroup → Default → Primary*
 */
export interface ImageGroupSliceDefaultPrimary {
  /**
   * Group Image field in *ImageGroup → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_group.default.primary.group_image[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  group_image: prismic.GroupField<
    Simplify<ImageGroupSliceDefaultPrimaryGroupImageItem>
  >;

  /**
   * Content field in *ImageGroup → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_group.default.primary.content[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  content: prismic.GroupField<
    Simplify<ImageGroupSliceDefaultPrimaryContentItem>
  >;
}

/**
 * Default variation for ImageGroup Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGroupSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageGroupSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageGroup*
 */
type ImageGroupSliceVariation = ImageGroupSliceDefault;

/**
 * ImageGroup Shared Slice
 *
 * - **API ID**: `image_group`
 * - **Description**: ImageGroup
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGroupSlice = prismic.SharedSlice<
  "image_group",
  ImageGroupSliceVariation
>;

/**
 * Primary content in *NewsLetter → Default → Primary*
 */
export interface NewsLetterSliceDefaultPrimary {
  /**
   * Background image field in *NewsLetter → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news_letter.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Heading field in *NewsLetter → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter heading here...
   * - **API ID Path**: news_letter.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *NewsLetter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter description here...
   * - **API ID Path**: news_letter.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Placeholder field in *NewsLetter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter placeholder here....
   * - **API ID Path**: news_letter.default.primary.place_holder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  place_holder: prismic.KeyTextField;

  /**
   * Button field in *NewsLetter → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter button name...
   * - **API ID Path**: news_letter.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for NewsLetter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsLetterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsLetterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NewsLetter*
 */
type NewsLetterSliceVariation = NewsLetterSliceDefault;

/**
 * NewsLetter Shared Slice
 *
 * - **API ID**: `news_letter`
 * - **Description**: NewsLetter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsLetterSlice = prismic.SharedSlice<
  "news_letter",
  NewsLetterSliceVariation
>;

/**
 * Primary content in *SalesSection → Default → Primary*
 */
export interface SalesSectionSliceDefaultPrimary {
  /**
   * Image field in *SalesSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sales_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * sale offer field in *SalesSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter offer detail.....
   * - **API ID Path**: sales_section.default.primary.sale_offer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sale_offer: prismic.RichTextField;

  /**
   * Heading field in *SalesSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter heading here...
   * - **API ID Path**: sales_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *SalesSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter sub description here...
   * - **API ID Path**: sales_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Button field in *SalesSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter your button name...
   * - **API ID Path**: sales_section.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Container Size field in *SalesSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter container size...
   * - **API ID Path**: sales_section.default.primary.container_size
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  container_size: prismic.KeyTextField;
}

/**
 * Default variation for SalesSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SalesSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SalesSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SalesSection*
 */
type SalesSectionSliceVariation = SalesSectionSliceDefault;

/**
 * SalesSection Shared Slice
 *
 * - **API ID**: `sales_section`
 * - **Description**: SalesSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SalesSectionSlice = prismic.SharedSlice<
  "sales_section",
  SalesSectionSliceVariation
>;

/**
 * Item in *SplitContent → Default → Primary → Content*
 */
export interface SplitContentSliceDefaultPrimaryContentItem {
  /**
   * Heading field in *SplitContent → Default → Primary → Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter heading here...
   * - **API ID Path**: split_content.default.primary.content[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *SplitContent → Default → Primary → Content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter sub description here...
   * - **API ID Path**: split_content.default.primary.content[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *SplitContent → Default → Primary*
 */
export interface SplitContentSliceDefaultPrimary {
  /**
   * Image field in *SplitContent → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: split_content.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Content field in *SplitContent → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: split_content.default.primary.content[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  content: prismic.GroupField<
    Simplify<SplitContentSliceDefaultPrimaryContentItem>
  >;
}

/**
 * Default variation for SplitContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SplitContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SplitContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SplitContent*
 */
type SplitContentSliceVariation = SplitContentSliceDefault;

/**
 * SplitContent Shared Slice
 *
 * - **API ID**: `split_content`
 * - **Description**: SplitContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SplitContentSlice = prismic.SharedSlice<
  "split_content",
  SplitContentSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      BlogsDocument,
      BlogsDocumentData,
      BlogsDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataNavItem,
      FooterDocumentDataSocialItem,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataNavItem,
      HeaderDocumentDataSocialItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      ArticleSectionSlice,
      ArticleSectionSliceDefaultPrimaryFeaturedBlogItem,
      ArticleSectionSliceDefaultPrimary,
      ArticleSectionSliceVariation,
      ArticleSectionSliceDefault,
      CardSectionSlice,
      CardSectionSliceDefaultPrimaryCardsItem,
      CardSectionSliceDefaultPrimary,
      CardSectionSliceCardWithCenterAlignPrimaryCardsItem,
      CardSectionSliceCardWithCenterAlignPrimary,
      CardSectionSliceVariation,
      CardSectionSliceDefault,
      CardSectionSliceCardWithCenterAlign,
      ContactFormSlice,
      ContactFormSliceDefaultPrimaryFormInputItem,
      ContactFormSliceDefaultPrimary,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      ContentSectionSlice,
      ContentSectionSliceDefaultPrimary,
      ContentSectionSliceVariation,
      ContentSectionSliceDefault,
      HeroSliderSlice,
      HeroSliderSliceDefaultPrimarySliderImageItem,
      HeroSliderSliceDefaultPrimary,
      HeroSliderSliceVariation,
      HeroSliderSliceDefault,
      ImageGroupSlice,
      ImageGroupSliceDefaultPrimaryGroupImageItem,
      ImageGroupSliceDefaultPrimaryContentItem,
      ImageGroupSliceDefaultPrimary,
      ImageGroupSliceVariation,
      ImageGroupSliceDefault,
      NewsLetterSlice,
      NewsLetterSliceDefaultPrimary,
      NewsLetterSliceVariation,
      NewsLetterSliceDefault,
      SalesSectionSlice,
      SalesSectionSliceDefaultPrimary,
      SalesSectionSliceVariation,
      SalesSectionSliceDefault,
      SplitContentSlice,
      SplitContentSliceDefaultPrimaryContentItem,
      SplitContentSliceDefaultPrimary,
      SplitContentSliceVariation,
      SplitContentSliceDefault,
    };
  }
}
