// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice = HeroSliderSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument;

/**
 * Item in *HeroSlider → Default → Primary → SliderImage*
 */
export interface HeroSliderSliceDefaultPrimarySliderImageItem {
  /**
   * Image field in *HeroSlider → Default → Primary → SliderImage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slider.default.primary.sliderImage[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *HeroSlider → Default → Primary*
 */
export interface HeroSliderSliceDefaultPrimary {
  /**
   * Heading field in *HeroSlider → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter heading here...
   * - **API ID Path**: hero_slider.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *HeroSlider → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter sub description here...
   * - **API ID Path**: hero_slider.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * SliderImage field in *HeroSlider → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slider.default.primary.sliderImage[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sliderImage: prismic.GroupField<
    Simplify<HeroSliderSliceDefaultPrimarySliderImageItem>
  >;
}

/**
 * Default variation for HeroSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSlider*
 */
type HeroSliderSliceVariation = HeroSliderSliceDefault;

/**
 * HeroSlider Shared Slice
 *
 * - **API ID**: `hero_slider`
 * - **Description**: HeroSlider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliderSlice = prismic.SharedSlice<
  "hero_slider",
  HeroSliderSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeroSliderSlice,
      HeroSliderSliceDefaultPrimarySliderImageItem,
      HeroSliderSliceDefaultPrimary,
      HeroSliderSliceVariation,
      HeroSliderSliceDefault,
    };
  }
}
